package:
  name: adaptivemd-dev
  version: "0.2.0"

source:
#  git_url: ../../.git
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - python
    - numpy
    - pymongo >=2.8
    - ujson

  run:
    - python
    - numpy
    - pymongo >=2.8
    - ujson

test:
  requires:
    - pytest
    - nbval
    - pyemma
    - openmm

  imports:
    - adaptivemd

  source_files:
    - examples/*

  commands:
    #- pip install radical.pilot
    - py.test -v --pyargs adaptivemd --doctest-modules
    #- py.test -v --nbval examples/

about:
  home: https://github.com/markovmodel/adaptivemd
  license: LGPL 2.1 or later
  summary: 'A wrapper for radical.pilot to run adaptive MD'
